### ISSUE TITLE
Error throw trying to create a warning in python3

### ISSUE THREAD

**Issue by westhomas** [pygraphviz/pygraphviz#112]
I'm receiving an error message when trying to produce a graphics file using django extensions. It seems there's a string concatenation error in pygraphviz, so I'm reporting it here.

```
# python3.4 manage.py graph_models -a -o blah.png
Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.4/dist-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.4/dist-packages/django/core/management/__init__.py", line 359, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.4/dist-packages/django/core/management/base.py", line 305, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.4/dist-packages/django/core/management/base.py", line 356, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.4/dist-packages/django_extensions/management/utils.py", line 58, in inner
    ret = func(self, *args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/django_extensions/management/commands/graph_models.py", line 164, in handle
    self.render_output_pygraphviz(dotdata, **options)
  File "/usr/local/lib/python3.4/dist-packages/django_extensions/management/commands/graph_models.py", line 204, in render_output_pygraphviz
    graph.layout(prog=kwargs['layout'])
  File "/usr/local/lib/python3.4/dist-packages/pygraphviz/agraph.py", line 1358, in layout
    data = self._run_prog(prog, ' '.join([args, "-T", fmt]))
  File "/usr/local/lib/python3.4/dist-packages/pygraphviz/agraph.py", line 1338, in _run_prog
    warnings.warn(b"".join(errors), RuntimeWarning)
TypeError: can't use a string pattern on a bytes-like object
```

```
django-extensions==1.7.4
pydot==1.2.2
pydotplus==2.0.2
pygraphviz==1.3.1
pyparsing==2.1.10
```

**Comment by hagberg** [comment]
I think we have that one fixed in the development version (also networkx-1.4rc1).
