### ISSUE TITLE
It raises key error if the node is string and the string is too long

### ISSUE THREAD

**Issue by xyz1396** [pygraphviz/pygraphviz#123]
`import networkx as nx 
import matplotlib.pyplot as plt
from networkx.drawing.nx_agraph import graphviz_layout
a=['1','21','22','32','312','322','432','4312','4312','5312','Node D_0__Bacteria D_1__Cyanobacteria D_2__Chloroplast D_3__Bryum argenteum var. argenteum D_4__Bryum argenteum var. argenteum D_5__Bryum argenteum var. argenteum D_6__Bryum argenteum var']
G = nx.DiGraph()
G.add_nodes_from(a)
pos = graphviz_layout(G)
nx.draw(G, pos,node_size = 100,with_labels = True)
plt.show()`

It raises key error because of a[10]

`Traceback (most recent call last):
  File "C:\Python34\lib\site-packages\pygraphviz\agraph.py", line 1566, in __new__
    nh = gv.agnode(graph.handle, n.encode(graph.encoding), _Action.find)
KeyError: 'agnode: no key'`

if I delete a[10] , or replace ‘Node D_0__Bacteria D_1__Cyanobacteria D_2__Chloroplast D_3__Bryum argenteum var. argenteum D_4__Bryum argenteum var. argenteum D_5__Bryum argenteum var. argenteum D_6__Bryum argenteum var’ with shorter string, the key error won't happen.

**Comment by weeinn** [comment]
Hi,

python-pygraphviz `1.12` with python `3.11`

I'm using pygraphviz to draw directed graph，obtain layout information. It has encountered a problem.
```python
import networkx as nx
import pandas as pd
from networkx.drawing.nx_agraph import pygraphviz_layout

network_df = pd.read_excel(r"C:\Users\xxxxx\Desktop\新建 XLSX 工作表.xlsx")
g = nx.from_pandas_edgelist(network_df, source='a', target='b', create_using=nx.DiGraph())

key = "xxxxxx市中西医结合医疗健康集团xxxxx分院（xxx市xxxxxxxxxx镇卫生院、xxx市xxxxxxxxxxx镇社区卫生服务中心）(15094137051)"
print(key in g.nodes())
pos = pygraphviz_layout(g, prog="dot")
```
It raises key error because of `xxxxxx市中西医结合医疗健康集团xxxxx分院（xxx市xxxxxxxxxx镇卫生院、xxx市xxxxxxxxxxx镇社区卫生服务中心）(15094137051)`

```python
Traceback (most recent call last):
  File "D:\Python3\Lib\site-packages\pygraphviz\agraph.py", line 1864, in __new__
    nh = gv.agnode(graph.handle, n.encode(graph.encoding), _Action.find)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Python3\Lib\site-packages\pygraphviz\graphviz.py", line 97, in agnode
    return _graphviz.agnode(g, name, createflag)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'agnode: no key'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\test.py", line 10, in <module>
    pos = pygraphviz_layout(g, prog="dot")
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Python3\Lib\site-packages\networkx\drawing\nx_agraph.py", line 311, in pygraphviz_layout
    node = pygraphviz.Node(A, n)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Python3\Lib\site-packages\pygraphviz\agraph.py", line 1867, in __new__
    raise KeyError(f"Node {n} not in graph.")
KeyError: 'Node xxxxxx市中西医结合医疗健康集团xxxxx分院（xxx市xxxxxxxxxx镇卫生院、xxx市xxxxxxxxxxx镇社区卫生服务中心）(15094137051) not in graph.'

Process finished with exit code 1
```
You can use test files to stably reproduce problems. [新建 XLSX 工作表.xlsx](https://github.com/user-attachments/files/18342848/XLSX.xlsx)
