### ISSUE TITLE
self-edges - KeyError: 'agedge: no key'  on  Windows

### ISSUE THREAD

**Issue by fpettinari** [pygraphviz/pygraphviz#137]
On *nix it works, on Windows it raises this error
with Graphviz 2.38.0.1

```
import pygraphviz as pgv
G = pgv.AGraph()
G.add_node('a')
G.add_edge('a', 'a')
```
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python27\lib\site-packages\pygraphviz\agraph.py", line 477, in add_edge
    eh = gv.agedge(self.handle, uh, vh, key, _Action.find)
KeyError: 'agedge: no key'
```

Started with pytransitions/transitions#258

**Comment by adamasstokhorst** [comment]
Posting in this issue again because it's still not resolved, at least on Windows. It's definitely not Graphviz's fault since a manually crafted dot file with self-loops still renders correctly.
```
> python -c "import pygraphviz as pgv; print pgv.__version__"
1.5

> dot -V
dot - graphviz version 2.38.0 (20140413.2041)

> python -c "import sys; print sys.version"
2.7.15 (v2.7.15:ca079a3ea3, Apr 30 2018, 16:22:17) [MSC v.1500 32 bit (Intel)]

> python -c "import pygraphviz as pgv; G = pgv.AGraph(strict=False); G.add_edge('a',
'a')"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Python27\lib\site-packages\pygraphviz\agraph.py", line 479, in add_edge
    eh = gv.agedge(self.handle, uh, vh, key, _Action.find)
KeyError: 'agedge: no key'
```

**Comment by 0x410c** [comment]
any update?

**Comment by jarrodmillman** [comment]
We no longer support 2.38.
