### ISSUE TITLE
Python 3 support

### ISSUE THREAD

**Issue by fjarri** [pygraphviz/pygraphviz#16]
Are there any plans to add the Python 3 support to Pygraphviz? 

I looked through the sources, and besides minor fixes (parentheses for ``print`` calls, one change in ``raise`` call, a few ``bytes`` to ``str`` transformations, some imports needs to be changed from relative to absolute), there seems to be the only problem I'm not sure how to approach: ``PyFile_AsFile`` used in the SWIG-generated interface is not present in the Python 3 API anymore, so some workaround needs to be added.

**Comment by brianaharder** [comment]
I'm trying to get pygraphviz 1.3rc2 to build on Python 3.4, with VS2010 on Windows 7.  I can build it for python 2.7 and VS2008 no problems, but on 3.4 I'm running into the _PyIOBase_Type error mentioned previously.

Pygraphiz was not correctly finding the paths for graphviz when trying to install with 3.4, I manually set them to:
include_dirs = "C:\Program Files (x86)\Graphviz2.38\include" 
library_dirs = "C:\Program Files (x86)\Graphviz2.38\lib\debug\lib" 
For whatever reason, it cannot find cgraph.lib looking at lib\release\lib despite the file being there.  Potentially problematic.  

```
C:\Users\Briana\Desktop\pygraphviz\pygraphviz>python3 setup.py clean build
library_dirs=C:\Program Files (x86)\Graphviz2.38\lib\debug\lib
include_dirs=C:\Program Files (x86)\Graphviz2.38\include
running clean
removing 'build\temp.win32-3.4' (and everything under it)
running build
running build_py
running build_ext
building 'pygraphviz._graphviz' extension
creating build\temp.win32-3.4
creating build\temp.win32-3.4\Release
creating build\temp.win32-3.4\Release\pygraphviz
C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\BIN\cl.exe /c /nologo /Ox
 /MD /W3 /GS- /DNDEBUG -DGVDLL "-IC:\Program Files (x86)\Graphviz2.38\include" -
IC:\Python34\include -IC:\Python34\include /Tcpygraphviz/graphviz_wrap.c /Fobuil
d\temp.win32-3.4\Release\pygraphviz/graphviz_wrap.obj
graphviz_wrap.c
pygraphviz/graphviz_wrap.c(3321) : warning C4047: 'return' : 'int' differs in le
vels of indirection from 'Agsym_t *'
C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\BIN\link.exe /DLL /nologo
 /INCREMENTAL:NO "/LIBPATH:C:\Program Files (x86)\Graphviz2.38\lib\debug\lib" /L
IBPATH:C:\Python34\libs /LIBPATH:C:\Python34\PCbuild cgraph.lib cdt.lib /EXPORT:
PyInit__graphviz build\temp.win32-3.4\Release\pygraphviz/graphviz_wrap.obj /OUT:
build\lib.win32-3.4\pygraphviz\_graphviz.pyd /IMPLIB:build\temp.win32-3.4\Releas
e\pygraphviz\_graphviz.lib /MANIFESTFILE:build\temp.win32-3.4\Release\pygraphviz
\_graphviz.pyd.manifest
   Creating library build\temp.win32-3.4\Release\pygraphviz\_graphviz.lib and ob
ject build\temp.win32-3.4\Release\pygraphviz\_graphviz.exp
graphviz_wrap.obj : error LNK2019: unresolved external symbol _PyIOBase_Type ref
erenced in function __wrap_agread
build\lib.win32-3.4\pygraphviz\_graphviz.pyd : fatal error LNK1120: 1 unresolved
 externals
error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 10.0\\VC\\BIN\\
link.exe' failed with exit status 1120
```

Using @Kagami 's patch https://github.com/Kagami/pygraphviz/commit/fe442dc16accb629c3feaf157af75f67ccabbd6e
pygraphviz does build, but, as noted, crashes on the smallest of tests.  

Not sure where to go from here.  If anyone needs a Win7/VS2010 test environment, I can run any potential patches, but I've got quite a bit of reading to do before I'm able to make any fixes myself.

**Comment by pfmoore** [comment]
Ignoring the issues with ```FILE*```, the supplied Graphviz binaries are 32-bit only. So it won't be possible to build for 64-bit Python without building your own Graphviz binaries.

As the Graphviz API passes ```FILE*``` values, it will segfault if the struct layout changes. It's possible that the layout differs between C runtimes on Windows. The Graphviz DLLs reference MSVCR90 (Visual Studio 2008), so again, it's quite possible that the supplied binaries won't work with MSVCR100 (Visual Studio 2010) which is what Python 3.4 is built with.

The long and short of it is that you'll probably need to do a custom build of graphviz to get binaries to work, with the one possible exception of 32-bit Python 2.

**Comment by brianaharder** [comment]
Thank you for the tips ptmoore.  

Patching pygraphviz1.3rc2 with fe442dc, I have now successfully built pygraphviz on Windows with 32bit python 3.2, which is the last version of python 3 still built with VS2008.  

Looks like that patch does fix the incompatibilities with python3/pygraphviz, and the remaining issues with python 3.4 are are due to MSVC version incompatibilities between Python/Graphviz.

**Comment by pfmoore** [comment]
Cool. I wonder if the graphviz project could be persuaded to provide 64-bit and/or VS2010 based builds?

**Comment by pfmoore** [comment]
I just had a quick go at trying to build 64-bit graphviz with VS2010, no joy. The solution files don't include a 64-bit target, and they don't convert cleanly to VS2010 format. It's going to take a lot more time and effort than I have available to produce the necessary builds, I'm afraid. I've asked on the graphviz-devel list whether the extra formats are (or could be made) available. We'll see what they say.

**Comment by cgohlke** [comment]
I put Windows binaries at <http://www.lfd.uci.edu/~gohlke/pythonlibs/#pygraphviz> if anyone wants to test pygraphviz‑1.3rc2+patch.

**Comment by pfmoore** [comment]
@cgohlke Interesting. WIth your build on 64-bit Python 3.4, pygraphviz.test() gives 21 failures and 1 error, but no sign of the C runtime compatibility issues I expected. Did you just link with the supplied libs? I wonder if it's a static build, although I'd still expect issues with 32-bit vs 64-bit. My tests were with ctypes loading the Graphviz dlls, and they failed on import.

But regardless of the technical details, great news!

**Comment by cgohlke** [comment]
First I build the 32 and 64 bit `cgraph.dll` and `cdt.dll` from the graphviz source code with Visual Studio 2008 and 2010. No need to build all the executables. Then I built pygraphviz against those DLLs and also distribute the DLLs next to the `_graphviz.pyd` extension. That way the DLLs should not interfere with an installed official Graphviz distribution, which is still required to run the executables.

When loading those DLLs with ctypes, first load `cdt.dll` using the full path, then load `cgraph.dll` using the full path. If you just load `cgraph.dll` or do not specify the full paths, ctypes might load the 32 bit VC9 DLLs from the Graphviz distribution.

**Comment by cgohlke** [comment]
Here are the test results for pygraphviz-1.3rc2-cp34-none-win_amd64 with graphviz-2.38.0. Looks like other python versions fail/error on the same tests.
```
FFFF..FF................FF............F................FF...........F.F.FF.FFFError: syntax error in line 36 near ''
.FFF..E.
======================================================================
ERROR: pygraphviz.tests.test_unicode.test_edge_encoding
----------------------------------------------------------------------
Traceback (most recent call last):
  File "X:\Python34\lib\site-packages\pygraphviz\agraph.py", line 1648, in __new__
    _Action.find)
KeyError: 'agedge: no key'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "X:\Python34\lib\site-packages\nose\case.py", line 198, in runTest
    self.test(*self.arg)
  File "X:\Python34\lib\site-packages\pygraphviz\tests\test_unicode.py", line 28, in test_edge_encoding
    e=A.get_edge(hello,hello)
  File "X:\Python34\lib\site-packages\pygraphviz\agraph.py", line 515, in get_edge
    return Edge(self, u, v, key)
  File "X:\Python34\lib\site-packages\pygraphviz\agraph.py", line 1650, in __new__
    raise KeyError("Edge %s-%s not in graph." % (source, target))
KeyError: 'Edge \u05e9\u05dc\u05d5\u05dd-\u05e9\u05dc\u05d5\u05dd not in graph.'

======================================================================
FAIL: pygraphviz.tests.test_attribute_defaults.test_default_attributes
----------------------------------------------------------------------
Traceback (most recent call last):
  File "X:\Python34\lib\site-packages\nose\case.py", line 198, in runTest
    self.test(*self.arg)
  File "X:\Python34\lib\site-packages\pygraphviz\tests\test_attribute_defaults.py", line 22, in test_default_attributes
    """.replace('\n', linesep))
AssertionError: 'strict digraph {\r\n  graph [label=test,\r\n    spam=eggs\r\n  ];\r\n}\r\n' != 'strict graph {\r\n  graph [label=test,\r\n    spam=eggs\r\n  ];\r\n}\r\n'
- strict digraph {
?        --
+ strict graph {
    graph [label=test,
      spam=eggs
    ];
  }


======================================================================
FAIL: pygraphviz.tests.test_attribute_defaults.test_graph_defaults
----------------------------------------------------------------------
Traceback (most recent call last):
  File "X:\Python34\lib\site-packages\nose\case.py", line 198, in runTest
    self.test(*self.arg)
  File "X:\Python34\lib\site-packages\pygraphviz\tests\test_attribute_defaults.py", line 47, in test_graph_defaults
    """.replace('\n', linesep))
AssertionError: 'strict digraph {\r\n  graph [pack=true,\r\n    rankdir=LR\r\n  ];\r\n}\r\n' != 'strict graph {\r\n  graph [pack=true,\r\n    rankdir=LR\r\n  ];\r\n}\r\n'
- strict digraph {
?        --
+ strict graph {
    graph [pack=true,
      rankdir=LR
    ];
  }


======================================================================
FAIL: pygraphviz.tests.test_attribute_defaults.test_node_defaults
----------------------------------------------------------------------
Traceback (most recent call last):
  File "X:\Python34\lib\site-packages\nose\case.py", line 198, in runTest
    self.test(*self.arg)
  File "X:\Python34\lib\site-packages\pygraphviz\tests\test_attribute_defaults.py", line 62, in test_node_defaults
    """.replace('\n', linesep)
AssertionError: 'strict digraph {\r\n  node [label=test];\r\n}\r\n' != 'strict graph {\r\n  node [label=test];\r\n}\r\n'

- strict digraph {
?        --
+ strict graph {
    node [label=test];
  }


======================================================================
FAIL: pygraphviz.tests.test_attribute_defaults.test_edge_defaults
----------------------------------------------------------------------
Traceback (most recent call last):
  File "X:\Python34\lib\site-packages\nose\case.py", line 198, in runTest
    self.test(*self.arg)
  File "X:\Python34\lib\site-packages\pygraphviz\tests\test_attribute_defaults.py", line 102, in test_edge_defaults
    """.replace('\n', linesep)
AssertionError: 'strict digraph {\r\n  edge [label=test];\r\n}\r\n' != 'strict graph {\r\n  edge [label=test];\r\n}\r\n'

- strict digraph {
?        --
+ strict graph {
    edge [label=test];
  }


======================================================================
FAIL: pygraphviz.tests.test_edge_attributes.test_edge_attributes
----------------------------------------------------------------------
Traceback (most recent call last):
  File "X:\Python34\lib\site-packages\nose\case.py", line 198, in runTest
    self.test(*self.arg)
  File "X:\Python34\lib\site-packages\pygraphviz\tests\test_edge_attributes.py", line 15, in test_edge_attributes
    """.replace('\n', linesep)
AssertionError: 'strict digraph {\r\n  1 -> 2   [label=test,\r\n    spam=eggs];\r\n}\r\n' != 'strict graph {\r\n  1 -- 2   [label=test,\r\n    spam=eggs];\r\n}\r\n'
- strict digraph {
?        --
+ strict graph {
-   1 -> 2   [label=test,
?      ^
+   1 -- 2   [label=test,
?      ^
      spam=eggs];
  }


======================================================================
FAIL: pygraphviz.tests.test_edge_attributes.test_edge_attributes2
----------------------------------------------------------------------
Traceback (most recent call last):
  File "X:\Python34\lib\site-packages\nose\case.py", line 198, in runTest
    self.test(*self.arg)
  File "X:\Python34\lib\site-packages\pygraphviz\tests\test_edge_attributes.py", line 32, in test_edge_attributes2
    """.replace('\n', linesep)
AssertionError: 'strict digraph {\r\n  1 -> 2   [label=test,\r\n    spam=eggs];\r\n}\r\n' != 'strict graph {\r\n  1 -- 2
   [label=test,\r\n    spam=eggs];\r\n}\r\n'
- strict digraph {
?        --
+ strict graph {
-   1 -> 2   [label=test,
?      ^
+   1 -- 2   [label=test,
?      ^
      spam=eggs];
  }


======================================================================
FAIL: pygraphviz.tests.test_graph.TestDiGraphOnly.test_graph_not_strict
----------------------------------------------------------------------
Traceback (most recent call last):
  File "X:\Python34\lib\site-packages\nose\case.py", line 198, in runTest
    self.test(*self.arg)
  File "X:\Python34\lib\site-packages\pygraphviz\tests\test_graph.py", line 249, in test_graph_not_strict
    assert_false(A.is_strict())
AssertionError: True is not false

======================================================================
FAIL: pygraphviz.tests.test_graph.TestDiGraphOnly.test_graph_strict
----------------------------------------------------------------------
Traceback (most recent call last):
  File "X:\Python34\lib\site-packages\nose\case.py", line 198, in runTest
    self.test(*self.arg)
  File "X:\Python34\lib\site-packages\pygraphviz\tests\test_graph.py", line 244, in test_graph_strict
    assert_equal(A.edges(), [('1', '2'), ('3', '3')])
AssertionError: Lists differ: [('1', '2')] != [('1', '2'), ('3', '3')]

Second list contains 1 additional elements.
First extra element 1:
('3', '3')

- [('1', '2')]
+ [('1', '2'), ('3', '3')]

======================================================================
FAIL: pygraphviz.tests.test_graph.TestDiGraphOnly.test_str
----------------------------------------------------------------------
Traceback (most recent call last):
  File "X:\Python34\lib\site-packages\nose\case.py", line 198, in runTest
    self.test(*self.arg)
  File "X:\Python34\lib\site-packages\pygraphviz\tests\test_graph.py", line 38, in test_str
    """.replace('\n', linesep)
AssertionError: 'strict digraph test {\r\n}\r\n' != 'strict graph test {\r\n}\r\n'
- strict digraph test {
?        --
+ strict graph test {
  }


======================================================================
FAIL: pygraphviz.tests.test_graph.TestGraph.test_graph_not_strict
----------------------------------------------------------------------
Traceback (most recent call last):
  File "X:\Python34\lib\site-packages\nose\case.py", line 198, in runTest
    self.test(*self.arg)
  File "X:\Python34\lib\site-packages\pygraphviz\tests\test_graph.py", line 249, in test_graph_not_strict
    assert_false(A.is_strict())
AssertionError: True is not false

======================================================================
FAIL: pygraphviz.tests.test_graph.TestGraph.test_graph_strict
----------------------------------------------------------------------
Traceback (most recent call last):
  File "X:\Python34\lib\site-packages\nose\case.py", line 198, in runTest
    self.test(*self.arg)
  File "X:\Python34\lib\site-packages\pygraphviz\tests\test_graph.py", line 244, in test_graph_strict
    assert_equal(A.edges(), [('1', '2'), ('3', '3')])
AssertionError: Lists differ: [('1', '2')] != [('1', '2'), ('3', '3')]

Second list contains 1 additional elements.
First extra element 1:
('3', '3')

- [('1', '2')]
+ [('1', '2'), ('3', '3')]

======================================================================
FAIL: pygraphviz.tests.test_graph.TestGraph.test_str
----------------------------------------------------------------------
Traceback (most recent call last):
  File "X:\Python34\lib\site-packages\nose\case.py", line 198, in runTest
    self.test(*self.arg)
  File "X:\Python34\lib\site-packages\pygraphviz\tests\test_graph.py", line 38, in test_str
    """.replace('\n', linesep)
AssertionError: 'strict digraph test {\r\n}\r\n' != 'strict graph test {\r\n}\r\n'
- strict digraph test {
?        --
+ strict graph test {
  }


======================================================================
FAIL: pygraphviz.tests.test_html.test_html
----------------------------------------------------------------------
Traceback (most recent call last):
  File "X:\Python34\lib\site-packages\nose\case.py", line 198, in runTest
    self.test(*self.arg)
  File "X:\Python34\lib\site-packages\pygraphviz\tests\test_html.py", line 23, in test_html
    """.replace('\n', linesep))
AssertionError: 'strict digraph {\r\n  graph [label=<Hello<BR/>Gr[218 chars]\r\n' != 'strict graph {\r\n  graph [label=<Hello<BR/>Grap[216 chars]\r\n'
- strict digraph {
?        --
+ strict graph {
    graph [label=<Hello<BR/>Graph>];
    node [label="\N"];
    {
      graph [label=<Hello<BR/>Subgraph>];
      sa     [label=<Hello<BR/>Subgraph Node b>];
    }
    a  [label=<Hello<BR/>Node>];
-   a -> b   [label=<Hello<BR/>Edge>];
?      ^
+   a -- b   [label=<Hello<BR/>Edge>];
?      ^
  }


======================================================================
FAIL: pygraphviz.tests.test_node_attributes.test_node_attribute
----------------------------------------------------------------------
Traceback (most recent call last):
  File "X:\Python34\lib\site-packages\nose\case.py", line 198, in runTest
    self.test(*self.arg)
  File "X:\Python34\lib\site-packages\pygraphviz\tests\test_node_attributes.py", line 16, in test_node_attribute
    """.replace('\n', linesep))
AssertionError: 'strict digraph {\r\n  node [label="\\N"];\r\n  1[38 chars]\r\n' != 'strict graph {\r\n  node [label="\\N"];\r\n  1  [36 chars]\r\n'
- strict digraph {
?        --
+ strict graph {
    node [label="\N"];
    1  [label=test,
      spam=eggs];
  }


======================================================================
FAIL: pygraphviz.tests.test_node_attributes.test_node_attributes2
----------------------------------------------------------------------
Traceback (most recent call last):
  File "X:\Python34\lib\site-packages\nose\case.py", line 198, in runTest
    self.test(*self.arg)
  File "X:\Python34\lib\site-packages\pygraphviz\tests\test_node_attributes.py", line 33, in test_node_attributes2
    """.replace('\n', linesep)
AssertionError: 'strict digraph {\r\n  node [label="\\N"];\r\n  1[38 chars]\r\n' != 'strict graph {\r\n  node [label="\\N"];\r\n  1  [36 chars]\r\n'
- strict digraph {
?        --
+ strict graph {
    node [label="\N"];
    1  [label=test,
      spam=eggs];
  }


======================================================================
FAIL: pygraphviz.tests.test_string.test_name
----------------------------------------------------------------------
Traceback (most recent call last):
  File "X:\Python34\lib\site-packages\nose\case.py", line 198, in runTest
    self.test(*self.arg)
  File "X:\Python34\lib\site-packages\pygraphviz\tests\test_string.py", line 12, in test_name
    """.replace('\n', linesep))
AssertionError: 'strict digraph {\r\n}\r\n' != 'strict graph {\r\n}\r\n'
- strict digraph {
?        --
+ strict graph {
  }


======================================================================
FAIL: pygraphviz.tests.test_string.test_string_representation_small
----------------------------------------------------------------------
Traceback (most recent call last):
  File "X:\Python34\lib\site-packages\nose\case.py", line 198, in runTest
    self.test(*self.arg)
  File "X:\Python34\lib\site-packages\pygraphviz\tests\test_string.py", line 30, in test_string_representation_small
    """.replace('\n', linesep)
AssertionError: 'strict digraph test {\r\n        1 -> 2;\r\n}\r\n' != 'strict graph test {\r\n        1 -- 2;\r\n}\r\n'

- strict digraph test {
?        --
+ strict graph test {
-         1 -> 2;
?            ^
+         1 -- 2;
?            ^
  }


======================================================================
FAIL: pygraphviz.tests.test_string.test_string_representation_large
----------------------------------------------------------------------
Traceback (most recent call last):
  File "X:\Python34\lib\site-packages\nose\case.py", line 198, in runTest
    self.test(*self.arg)
  File "X:\Python34\lib\site-packages\pygraphviz\tests\test_string.py", line 50, in test_string_representation_large
    """.replace('\n', linesep))
AssertionError: 'strict digraph "test graph" {\r\n        1 -> 2;[173 chars]\r\n' != 'strict graph "test graph" {\r\n
     1 -- 2;\r[171 chars]\r\n'
Diff is 711 characters long. Set self.maxDiff to None to see it.

======================================================================
FAIL: pygraphviz.tests.test_subgraph.test_subgraph
----------------------------------------------------------------------
Traceback (most recent call last):
  File "X:\Python34\lib\site-packages\nose\case.py", line 198, in runTest
    self.test(*self.arg)
  File "X:\Python34\lib\site-packages\pygraphviz\tests\test_subgraph.py", line 17, in test_subgraph
    """.replace('\n', linesep))
AssertionError: 'strict digraph {\r\n  {\r\n    graph [label=foo][28 chars]\r\n' != 'strict graph {\r\n  {\r\n    graph[label=foo];\[26 chars]\r\n'
- strict digraph {
?        --
+ strict graph {
    {
      graph [label=foo];
-     1 -> 2;
?        ^
+     1 -- 2;
?        ^
    }
  }


======================================================================
FAIL: pygraphviz.tests.test_subgraph.test_subgraph_cluster
----------------------------------------------------------------------
Traceback (most recent call last):
  File "X:\Python34\lib\site-packages\nose\case.py", line 198, in runTest
    self.test(*self.arg)
  File "X:\Python34\lib\site-packages\pygraphviz\tests\test_subgraph.py", line 35, in test_subgraph_cluster
    """.replace('\n', linesep))
AssertionError: 'strict digraph {\r\n  graph [label=foo];\r\n  {\[70 chars]\r\n' != 'strict graph {\r\n  graph [label=foo];\r\n  {\r\[68 chars]\r\n'
- strict digraph {
?        --
+ strict graph {
    graph [label=foo];
    {
      graph [label=<Hello<BR/>World>];
      sa;
    }
    a;
  }


======================================================================
FAIL: pygraphviz.tests.test_subgraph.test_subgraph_cluster_attribute
----------------------------------------------------------------------
Traceback (most recent call last):
  File "X:\Python34\lib\site-packages\nose\case.py", line 198, in runTest
    self.test(*self.arg)
  File "X:\Python34\lib\site-packages\pygraphviz\tests\test_subgraph.py", line 51, in test_subgraph_cluster_attribute
    """.replace('\n', linesep))
AssertionError: 'strict digraph {\r\n  node [foo=baz];\r\n  subgr[59 chars]\r\n' != 'strict graph {\r\n  node [foo=baz];\r\n  subgrap[57 chars]\r\n'
- strict digraph {
?        --
+ strict graph {
    node [foo=baz];
    subgraph cluster_a {
      graph [foo=bar];
    }
    a;
  }


----------------------------------------------------------------------
Ran 86 tests in 0.453s

FAILED (errors=1, failures=21)
```

**Comment by DanielOaks** [comment]
Just wanted to say, using this with networkx on Py3 for one of my own projects at the moment, and it's working great. Had to install it via git+ instead of the current pypi version, but even so I can't wait 'til it's ready to go proper. Thanks for the awesome work, guys!

**Comment by hagberg** [comment]
Hi @DanielOaks, thanks for the report.  We will make an official release soon.

@cgohlke the tests pass for me with 

```bash
[pygraphviz-master ((pygraphviz-1.3rc2))]$ dot -V
dot - graphviz version 2.38.0 (20140413.2041)
[pygraphviz-master ((pygraphviz-1.3rc2))]$ nosetests-2.7 --verbosity=0  pygraphviz
----------------------------------------------------------------------
Ran 108 tests in 0.424s

OK
```

**Comment by Alexis-benoist** [comment]
Hello,

I tried to install pygraphviz 1.3rc2 with python 3.4.3 on OSX and it failed with this [stacktrace](https://gist.github.com/Alexis-benoist/385e696df2a4226512df)
Do you guys know why?

Cheers,
Alexis.

**Comment by mmarkov** [comment]
@Alexis-benoist, based on your stack trace it is because paths are binary and not strings:

`library_dirs=b'/usr/local/Cellar/graphviz/2.38.0/lib'
include_dirs=b'/usr/local/Cellar/graphviz/2.38.0/include/graphviz'`

I guess it is a bug in https://github.com/mmarkov/pygraphviz/blob/master/setup_extra.py - I tried to fix it with this commit https://github.com/pygraphviz/pygraphviz/commit/1d1e37147e6acc938e0822cf79e44d7200522c8a commit. As far as I see, this commit is not part of 1.3rc2 published at pypi. I recommend you try using direct reference to master in requirements.txt file while this version is not released yet.

**Comment by Alexis-benoist** [comment]
Ok, Thanks! Do you know like when the final will be push on PyPi I would like to include it on my [module](https://github.com/Alexis-benoist/eralchemy) ?

**Comment by hagberg** [comment]
pygraphviz is working with Python3.  
Please open a new issue with any item that still needs to be addressed for specific operating systems or setups.

**Comment by dmr** [comment]
I tried to install pygraphviz with `pip install pygraphviz` and the result was `SyntaxError: print "To install, run 'python setup.py install'"`

--> pygraphviz 1.3 is still not the default version that is installed. What is blocking pygraphviz 1.3? #64 addresses the same issue :(

**Comment by hagberg** [comment]
Right now this is blocking the release https://github.com/pygraphviz/pygraphviz/issues/65
