### ISSUE TITLE
trailing character in dot file doesn't cause parse error but breaks Agraph constructor

### ISSUE THREAD

**Issue by jcaplan** [pygraphviz/pygraphviz#171]
given the file hello.gv.txt:
```
digraph G {Hello->World}"
```
with a trailing " character. Dot is still able to parse the file.
Calling:
```
graph = AGraph('./hello.gv.txt')
```
also succeeds.
However, calling Agraph again will always cause a DotError
```
graph = AGraph('./hello.gv.txt')
graph = AGraph('./profile.gv.txt')
```
results in:
```
Error: syntax error in line 1 near '"'
Traceback (most recent call last):
  File "/home/jcaplan/.local/lib/python3.5/site-packages/pygraphviz/agraph.py", line 1201, in read
    self.handle = gv.agread(fh, None)
ValueError: agread: bad input data

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test_graphviz.py", line 5, in <module>
    graph = AGraph('./profile.gv.txt')
  File "/home/jcaplan/.local/lib/python3.5/site-packages/pygraphviz/agraph.py", line 162, in __init__
    self.read(filename)
  File "/home/jcaplan/.local/lib/python3.5/site-packages/pygraphviz/agraph.py", line 1203, in read
    raise DotError
pygraphviz.agraph.DotError
```
The behaviour is odd and the error message is super confusing (especially if you don't catch the typo in the hello file). I'm guessing there is some shared character buffer somewhere which is not being cleared properly.

**Comment by rossbar** [comment]
FWIW this *seems* to be a graphviz issue, or at least it was fixed by graphviz. The tricky part is knowing exactly which version of graphviz introduced the fix --- I've narrowed it down to >v12.2.1 - see gh-620 for details.
