### ISSUE TITLE
Test failures with Graphviz 2.40.1

### ISSUE THREAD

**Issue by rekado** [pygraphviz/pygraphviz#175]
I've packaged pygraphviz for GNU Guix.  We're using Graphviz 2.40.1 and I'm currently building with Python 3.6.5.

23 of the 95 tests fail, most of them due to what seems like inconsequential differences in the Graphviz output.  Here's one example:

~~~
======================================================================
FAIL: pygraphviz.tests.test_subgraph.test_subgraph_cluster_attribute
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/gnu/store/am211hm7jb2y0schyzz4bx68z1i19l0h-python-nose-1.3.7/lib/python3.6/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/tmp/guix-build-python-pygraphviz-1.5.drv-0/source/pygraphviz/tests/test_subgraph.py", line 51, in test_subgraph_cluster_attribute
    """.replace('\n', linesep))
AssertionError: 'strict graph "" {\n  node [foo=baz];\n  subgraph clust[40 chars]n}\n' != 'strict graph {\n  node [foo=baz];\n  subgraph cluster_[37 chars]n}\n'
- strict graph "" {
?              ---
+ strict graph {
    node [foo=baz];
    subgraph cluster_a {
      graph [foo=bar];
    }
    a;
  }

    """Fail immediately, with the given message."""
>>  raise self.failureException('\'strict graph "" {\\n  node [foo=baz];\\n  subgraph clust[40 chars]n}\\n\' != \'strict graph {\\n  node [foo=baz];\\n  subgraph cluster_[37 chars]n}\\n\'\n- strict graph "" {\n?              ---\n+ strict graph {\n    node [foo=baz];\n    subgraph cluster_a {\n      graph [foo=bar];\n    }\n    a;\n  }\n')
~~~

Are these really unproblematic differences?  If so, can the tests be made a little more tolerant? 

Thanks!

--
Ricardo

**Comment by rekado** [comment]
Thank you for the explanation.  I've built it successfully with GraphViz 2.38.
