### ISSUE TITLE
Unable to install pygraphviz under RHEL 7.4

### ISSUE THREAD

**Issue by Pavche** [pygraphviz/pygraphviz#180]
When I install pygraphviz under Red Hat Enterprise Linux 7.4
buy using command: `pip install pygraphviz --user`
then I get error:
```
  Running setup.py install for pygraphviz ... error
    Complete output from command /usr/bin/python3.4 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-_j6rfhl8/pygraphviz/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-fm768mhw/install-record.txt --single-version-externally-managed --compile --user --prefix=:
    running install
    Trying dpkg
    Failed to find dpkg
    Trying pkg-config
    Package libcgraph was not found in the pkg-config search path.
    Perhaps you should add the directory containing `libcgraph.pc'
    to the PKG_CONFIG_PATH environment variable
    No package 'libcgraph' found
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-_j6rfhl8/pygraphviz/setup.py", line 93, in <module>
        tests_require=['nose>=1.3.7', 'doctest-ignore-unicode>=0.1.2', 'mock>=2.0.0'],
      File "/usr/lib64/python3.4/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/lib64/python3.4/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/usr/lib64/python3.4/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/tmp/pip-install-_j6rfhl8/pygraphviz/setup_commands.py", line 44, in modified_run
        self.include_path, self.library_path = get_graphviz_dirs()
      File "/tmp/pip-install-_j6rfhl8/pygraphviz/setup_extra.py", line 162, in get_graphviz_dirs
        include_dirs, library_dirs = _try_configure(include_dirs, library_dirs, _pkg_config)
      File "/tmp/pip-install-_j6rfhl8/pygraphviz/setup_extra.py", line 117, in _try_configure
        i, l = try_function()
      File "/tmp/pip-install-_j6rfhl8/pygraphviz/setup_extra.py", line 72, in _pkg_config
        output = S.check_output(['pkg-config', '--libs-only-L', 'libcgraph'])
      File "/usr/lib64/python3.4/subprocess.py", line 617, in check_output
        raise CalledProcessError(retcode, process.args, output=output)
    subprocess.CalledProcessError: Command '['pkg-config', '--libs-only-L', 'libcgraph']' returned non-zero exit status 1
    
    ----------------------------------------
Command "/usr/bin/python3.4 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-_j6rfhl8/pygraphviz/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-fm768mhw/install-record.txt --single-version-externally-managed --compile --user --prefix=" failed with error code 1 in /tmp/pip-install-_j6rfhl8/pygraphviz/
```

**Details**

**Python version**

```
python-2.7.5-58.el7.x86_64
python2-pip-8.1.2-6.el7.noarch
python34-3.4.9-1.el7.x86_64
python34-pip-8.1.2-6.el7.noarch
```

**Python module version**
```
doctest-ignore-unicode 0.1.2  
mock                   2.0.0  
nose                   1.3.7 
```

**Comment by Pavche** [comment]
After installing package `graphviz-devel`, I was able to install Python
module `pygraphviz`.
