### ISSUE TITLE
pygraphviz cannot be installed with pip

### ISSUE THREAD

**Issue by Mikaela** [pygraphviz/pygraphviz#20]
```
% 1 python3 --version;pip --version;pip install pygraphviz
Python 3.3.5
pip 1.5.4 from /home/users/mkaysi/.pyenv/versions/3.3.5/lib/python3.3/site-packages/pip-1.5.4-py3.3.egg (python 3.3)
Downloading/unpacking pygraphviz
  Downloading pygraphviz-1.2.tar.gz (90kB): 90kB downloaded
  Running setup.py (path:/tmp/pip_build_mkaysi/pygraphviz/setup.py) egg_info for package pygraphviz
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/tmp/pip_build_mkaysi/pygraphviz/setup.py", line 23
        print "To install, run 'python setup.py install'"
                                                        ^
    SyntaxError: invalid syntax
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "/tmp/pip_build_mkaysi/pygraphviz/setup.py", line 23

    print "To install, run 'python setup.py install'"

                                                    ^

SyntaxError: invalid syntax

----------------------------------------
Cleaning up...
Command python setup.py egg_info failed with error code 1 in /tmp/pip_build_mkaysi/pygraphviz
Storing debug log for failure in /home/users/mkaysi/.pip/pip.log
```

```
------------------------------------------------------------
/home/users/mkaysi/.pyenv/versions/3.3.5/bin/pip run on Mon May 26 19:59:10 2014
Downloading/unpacking pygraphviz
  Getting page https://pypi.python.org/simple/pygraphviz/
  URLs to search for versions for pygraphviz:
  * https://pypi.python.org/simple/pygraphviz/
  Analyzing links from page https://pypi.python.org/simple/pygraphviz/
    Skipping link https://pypi.python.org/packages/2.4/p/pygraphviz/pygraphviz-0.99-py2.4-linux-i686.egg#md5=82581a5e6021989c904fed1ee742cd99 (from https://pypi.python.org/simple/pygraphviz/); unknown archive format: .egg
    Skipping link https://pypi.python.org/packages/2.4/p/pygraphviz/pygraphviz-0.99.1-py2.4-linux-i686.egg#md5=b9c89f19746e57cfab51ab281381a609 (from https://pypi.python.org/simple/pygraphviz/); unknown archive format: .egg
    Skipping link https://pypi.python.org/packages/2.5/p/pygraphviz/pygraphviz-0.99-py2.5-linux-i686.egg#md5=359c0c5bee29cf7365707ff536ab6892 (from https://pypi.python.org/simple/pygraphviz/); unknown archive format: .egg
    Skipping link https://pypi.python.org/packages/2.5/p/pygraphviz/pygraphviz-0.99.1-py2.5-linux-i686.egg#md5=b440a72ab04a80eb48dd09aed2121bf5 (from https://pypi.python.org/simple/pygraphviz/); unknown archive format: .egg
    Found link https://pypi.python.org/packages/source/p/pygraphviz/pygraphviz-0.34.tar.gz#md5=550b94a2cbb1827af1a23d87c4e04810 (from https://pypi.python.org/simple/pygraphviz/), version: 0.34
    Found link https://pypi.python.org/packages/source/p/pygraphviz/pygraphviz-0.34.zip#md5=775cec62c3da868553f0a7b89ec1dcc2 (from https://pypi.python.org/simple/pygraphviz/), version: 0.34
    Found link https://pypi.python.org/packages/source/p/pygraphviz/pygraphviz-0.35.tar.gz#md5=28bf924a706e073fc9861f0beeb0b9aa (from https://pypi.python.org/simple/pygraphviz/), version: 0.35
    Found link https://pypi.python.org/packages/source/p/pygraphviz/pygraphviz-0.35.zip#md5=fa41fbca0edeccf6ec044294dab4c7ca (from https://pypi.python.org/simple/pygraphviz/), version: 0.35
    Found link https://pypi.python.org/packages/source/p/pygraphviz/pygraphviz-0.36.tar.gz#md5=13c32c59933dfc3de3edd092b5b3b08c (from https://pypi.python.org/simple/pygraphviz/), version: 0.36
    Found link https://pypi.python.org/packages/source/p/pygraphviz/pygraphviz-0.36.zip#md5=2ad831f8014d782fee23f650aa0cd535 (from https://pypi.python.org/simple/pygraphviz/), version: 0.36
    Found link https://pypi.python.org/packages/source/p/pygraphviz/pygraphviz-0.37.tar.gz#md5=3379f23497bffe549269cfcf00de099b (from https://pypi.python.org/simple/pygraphviz/), version: 0.37
    Found link https://pypi.python.org/packages/source/p/pygraphviz/pygraphviz-0.37.zip#md5=0f935a2517341e27886e21216525a9cd (from https://pypi.python.org/simple/pygraphviz/), version: 0.37
    Found link https://pypi.python.org/packages/source/p/pygraphviz/pygraphviz-0.99.1.tar.gz#md5=5381633f9538804b24046eb96474668d (from https://pypi.python.org/simple/pygraphviz/), version: 0.99.1
    Found link https://pypi.python.org/packages/source/p/pygraphviz/pygraphviz-0.99.1.zip#md5=33a9d11592a10dd0e9de6d587db5b101 (from https://pypi.python.org/simple/pygraphviz/), version: 0.99.1
    Found link https://pypi.python.org/packages/source/p/pygraphviz/pygraphviz-0.99.tar.gz#md5=b0052a2b1d3a9cfb806eb8b28abf8e2d (from https://pypi.python.org/simple/pygraphviz/), version: 0.99
    Found link https://pypi.python.org/packages/source/p/pygraphviz/pygraphviz-0.99.zip#md5=1625afb50d6d2d4dd833ee2f9810bcd0 (from https://pypi.python.org/simple/pygraphviz/), version: 0.99
    Found link https://pypi.python.org/packages/source/p/pygraphviz/pygraphviz-1.0.tar.gz#md5=f0cb263f4f56a0ba5c10e3ddcbbdf314 (from https://pypi.python.org/simple/pygraphviz/), version: 1.0
    Found link https://pypi.python.org/packages/source/p/pygraphviz/pygraphviz-1.0.zip#md5=52e0b79451e031e9cb7ee3b05f75f227 (from https://pypi.python.org/simple/pygraphviz/), version: 1.0
    Found link https://pypi.python.org/packages/source/p/pygraphviz/pygraphviz-1.0rc1.tar.gz#md5=6ec2327bd60d5f045195c5b60ccb269e (from https://pypi.python.org/simple/pygraphviz/), version: 1.0rc1
    Found link https://pypi.python.org/packages/source/p/pygraphviz/pygraphviz-1.0rc1.zip#md5=c226038dd78d59af3519d281eb4fd7a8 (from https://pypi.python.org/simple/pygraphviz/), version: 1.0rc1
    Found link https://pypi.python.org/packages/source/p/pygraphviz/pygraphviz-1.0rc2.tar.gz#md5=b7b728837da91be1d07d6670225a95e7 (from https://pypi.python.org/simple/pygraphviz/), version: 1.0rc2
    Found link https://pypi.python.org/packages/source/p/pygraphviz/pygraphviz-1.0rc2.zip#md5=f2c3ea804fffe4c902c92753238931a5 (from https://pypi.python.org/simple/pygraphviz/), version: 1.0rc2
    Found link https://pypi.python.org/packages/source/p/pygraphviz/pygraphviz-1.0rc3.tar.gz#md5=fbe24ba9e3cf8fc9705e7acbc582f63d (from https://pypi.python.org/simple/pygraphviz/), version: 1.0rc3
    Found link https://pypi.python.org/packages/source/p/pygraphviz/pygraphviz-1.0rc3.zip#md5=1aab6d8e039041655e6bdd0789fb2313 (from https://pypi.python.org/simple/pygraphviz/), version: 1.0rc3
    Found link https://pypi.python.org/packages/source/p/pygraphviz/pygraphviz-1.0rc4.tar.gz#md5=9d2d2e04e86bde7699db22cd19758424 (from https://pypi.python.org/simple/pygraphviz/), version: 1.0rc4
    Found link https://pypi.python.org/packages/source/p/pygraphviz/pygraphviz-1.0rc4.zip#md5=669ece9e6cc2eed1826b61eee854cb28 (from https://pypi.python.org/simple/pygraphviz/), version: 1.0rc4
    Found link https://pypi.python.org/packages/source/p/pygraphviz/pygraphviz-1.0rc5.tar.gz#md5=5853cde70a1a26a3b1922ce90759f5d7 (from https://pypi.python.org/simple/pygraphviz/), version: 1.0rc5
    Found link https://pypi.python.org/packages/source/p/pygraphviz/pygraphviz-1.0rc5.zip#md5=908f0127a72c441faa650f6f9d7cdb17 (from https://pypi.python.org/simple/pygraphviz/), version: 1.0rc5
    Found link https://pypi.python.org/packages/source/p/pygraphviz/pygraphviz-1.0rc6.tar.gz#md5=a8bafcfbd1b4c039dd116d53871e5fcc (from https://pypi.python.org/simple/pygraphviz/), version: 1.0rc6
    Found link https://pypi.python.org/packages/source/p/pygraphviz/pygraphviz-1.0rc6.zip#md5=0d7b2e76d6914b0e3e58d6a99933919a (from https://pypi.python.org/simple/pygraphviz/), version: 1.0rc6
    Found link https://pypi.python.org/packages/source/p/pygraphviz/pygraphviz-1.1.tar.gz#md5=5c206838ce81180557e29135e93b2461 (from https://pypi.python.org/simple/pygraphviz/), version: 1.1
    Found link https://pypi.python.org/packages/source/p/pygraphviz/pygraphviz-1.1.zip#md5=9b9958f10bdf29c06d9f43e225f6ac0c (from https://pypi.python.org/simple/pygraphviz/), version: 1.1
    Found link https://pypi.python.org/packages/source/p/pygraphviz/pygraphviz-1.1rc1.tar.gz#md5=7e709a8bf8d5103b461a5f54a399ef0d (from https://pypi.python.org/simple/pygraphviz/), version: 1.1rc1
    Found link https://pypi.python.org/packages/source/p/pygraphviz/pygraphviz-1.1rc1.zip#md5=cb5b015ad61eb200ab40003481f620e2 (from https://pypi.python.org/simple/pygraphviz/), version: 1.1rc1
    Found link https://pypi.python.org/packages/source/p/pygraphviz/pygraphviz-1.2.tar.gz#md5=dbe3fa55e59a5d7e3bd924511b3275c4 (from https://pypi.python.org/simple/pygraphviz/), version: 1.2
    Found link https://pypi.python.org/packages/source/p/pygraphviz/pygraphviz-1.2.zip#md5=90c728a8db276eede4e3af2f990a8985 (from https://pypi.python.org/simple/pygraphviz/), version: 1.2
    Skipping link http://networkx.github.io (from https://pypi.python.org/simple/pygraphviz/); not a file
    Skipping link http://networkx.lanl.gov/download (from https://pypi.python.org/simple/pygraphviz/); not a file
    Skipping link http://networkx.lanl.gov/download/pygraphviz (from https://pypi.python.org/simple/pygraphviz/); not a file
    Skipping link http://networkx.lanl.gov/pygraphviz (from https://pypi.python.org/simple/pygraphviz/); not a file
    Skipping link http://networkx.lanl.gov/pygraphviz/ (from https://pypi.python.org/simple/pygraphviz/); not a file
    Skipping link http://networkx.lanl.gov/wiki/download (from https://pypi.python.org/simple/pygraphviz/); not a file
    Skipping link http://pygraphviz.github.io (from https://pypi.python.org/simple/pygraphviz/); not a file
    Skipping link http://sourceforge.net/project/showfiles.php?group_id=122233&package_id=161979 (from https://pypi.python.org/simple/pygraphviz/); unknown archive format: .php
    Skipping link https://pypi.python.org/pypi/pygraphviz (from https://pypi.python.org/simple/pygraphviz/); not a file
  Not searching http://networkx.lanl.gov/download (from https://pypi.python.org/simple/pygraphviz/) for files because external urls are disallowed.
  Not searching http://networkx.lanl.gov/download/pygraphviz (from https://pypi.python.org/simple/pygraphviz/) for files because external urls are disallowed.
  Not searching http://networkx.lanl.gov/download/pygraphviz (from https://pypi.python.org/simple/pygraphviz/) for files because external urls are disallowed.
  Not searching http://networkx.lanl.gov/download/pygraphviz (from https://pypi.python.org/simple/pygraphviz/) for files because external urls are disallowed.
  Not searching http://networkx.lanl.gov/download/pygraphviz (from https://pypi.python.org/simple/pygraphviz/) for files because external urls are disallowed.
  Not searching http://networkx.lanl.gov/download/pygraphviz (from https://pypi.python.org/simple/pygraphviz/) for files because external urls are disallowed.
  Not searching http://networkx.lanl.gov/download/pygraphviz (from https://pypi.python.org/simple/pygraphviz/) for files because external urls are disallowed.
  Not searching http://networkx.lanl.gov/download/pygraphviz (from https://pypi.python.org/simple/pygraphviz/) for files because external urls are disallowed.
  Not searching http://networkx.lanl.gov/download/pygraphviz (from https://pypi.python.org/simple/pygraphviz/) for files because external urls are disallowed.
  Not searching http://networkx.lanl.gov/download/pygraphviz (from https://pypi.python.org/simple/pygraphviz/) for files because external urls are disallowed.
  Not searching http://networkx.lanl.gov/pygraphviz (from https://pypi.python.org/simple/pygraphviz/) for files because external urls are disallowed.
  Not searching http://networkx.lanl.gov/pygraphviz (from https://pypi.python.org/simple/pygraphviz/) for files because external urls are disallowed.
  Not searching http://networkx.lanl.gov/pygraphviz (from https://pypi.python.org/simple/pygraphviz/) for files because external urls are disallowed.
  Not searching http://networkx.lanl.gov/pygraphviz (from https://pypi.python.org/simple/pygraphviz/) for files because external urls are disallowed.
  Not searching http://networkx.lanl.gov/pygraphviz (from https://pypi.python.org/simple/pygraphviz/) for files because external urls are disallowed.
  Not searching http://networkx.lanl.gov/pygraphviz (from https://pypi.python.org/simple/pygraphviz/) for files because external urls are disallowed.
  Not searching http://networkx.lanl.gov/pygraphviz (from https://pypi.python.org/simple/pygraphviz/) for files because external urls are disallowed.
  Not searching http://networkx.lanl.gov/pygraphviz (from https://pypi.python.org/simple/pygraphviz/) for files because external urls are disallowed.
  Not searching http://networkx.lanl.gov/pygraphviz (from https://pypi.python.org/simple/pygraphviz/) for files because external urls are disallowed.
  Not searching http://networkx.lanl.gov/pygraphviz (from https://pypi.python.org/simple/pygraphviz/) for files because external urls are disallowed.
  Not searching http://networkx.lanl.gov/pygraphviz (from https://pypi.python.org/simple/pygraphviz/) for files because external urls are disallowed.
  Not searching http://networkx.lanl.gov/pygraphviz (from https://pypi.python.org/simple/pygraphviz/) for files because external urls are disallowed.
  Not searching http://networkx.lanl.gov/pygraphviz (from https://pypi.python.org/simple/pygraphviz/) for files because external urls are disallowed.
  Not searching http://networkx.lanl.gov/pygraphviz (from https://pypi.python.org/simple/pygraphviz/) for files because external urls are disallowed.
  Not searching http://networkx.lanl.gov/pygraphviz (from https://pypi.python.org/simple/pygraphviz/) for files because external urls are disallowed.
  Not searching http://networkx.lanl.gov/pygraphviz/ (from https://pypi.python.org/simple/pygraphviz/) for files because external urls are disallowed.
  Not searching http://networkx.lanl.gov/pygraphviz/ (from https://pypi.python.org/simple/pygraphviz/) for files because external urls are disallowed.
  Not searching http://networkx.lanl.gov/pygraphviz/ (from https://pypi.python.org/simple/pygraphviz/) for files because external urls are disallowed.
  Not searching http://networkx.lanl.gov/pygraphviz/ (from https://pypi.python.org/simple/pygraphviz/) for files because external urls are disallowed.
  Not searching http://networkx.lanl.gov/pygraphviz/ (from https://pypi.python.org/simple/pygraphviz/) for files because external urls are disallowed.
  Not searching http://networkx.lanl.gov/wiki/download (from https://pypi.python.org/simple/pygraphviz/) for files because external urls are disallowed.
  Not searching http://networkx.lanl.gov/wiki/download (from https://pypi.python.org/simple/pygraphviz/) for files because external urls are disallowed.
  Not searching http://networkx.lanl.gov/wiki/download (from https://pypi.python.org/simple/pygraphviz/) for files because external urls are disallowed.
  Not searching http://networkx.lanl.gov/wiki/download (from https://pypi.python.org/simple/pygraphviz/) for files because external urls are disallowed.
  Not searching http://networkx.lanl.gov/wiki/download (from https://pypi.python.org/simple/pygraphviz/) for files because external urls are disallowed.
  Not searching http://pygraphviz.github.io (from https://pypi.python.org/simple/pygraphviz/) for files because external urls are disallowed.
  Not searching http://sourceforge.net/project/showfiles.php?group_id=122233&package_id=161979 (from https://pypi.python.org/simple/pygraphviz/) for files because external urls are disallowed.
  Not searching http://sourceforge.net/project/showfiles.php?group_id=122233&package_id=161979 (from https://pypi.python.org/simple/pygraphviz/) for files because external urls are disallowed.
  Not searching http://sourceforge.net/project/showfiles.php?group_id=122233&package_id=161979 (from https://pypi.python.org/simple/pygraphviz/) for files because external urls are disallowed.
  Not searching http://sourceforge.net/project/showfiles.php?group_id=122233&package_id=161979 (from https://pypi.python.org/simple/pygraphviz/) for files because external urls are disallowed.
  Not searching http://sourceforge.net/project/showfiles.php?group_id=122233&package_id=161979 (from https://pypi.python.org/simple/pygraphviz/) for files because external urls are disallowed.
  Not searching https://pypi.python.org/pypi/pygraphviz (from https://pypi.python.org/simple/pygraphviz/) for files because external urls are disallowed.
  Ignoring link https://pypi.python.org/packages/source/p/pygraphviz/pygraphviz-1.0rc1.tar.gz#md5=6ec2327bd60d5f045195c5b60ccb269e (from https://pypi.python.org/simple/pygraphviz/), version 1.0rc1 is a pre-release (use --pre to allow).
  Ignoring link https://pypi.python.org/packages/source/p/pygraphviz/pygraphviz-1.0rc1.zip#md5=c226038dd78d59af3519d281eb4fd7a8 (from https://pypi.python.org/simple/pygraphviz/), version 1.0rc1 is a pre-release (use --pre to allow).
  Ignoring link https://pypi.python.org/packages/source/p/pygraphviz/pygraphviz-1.0rc2.tar.gz#md5=b7b728837da91be1d07d6670225a95e7 (from https://pypi.python.org/simple/pygraphviz/), version 1.0rc2 is a pre-release (use --pre to allow).
  Ignoring link https://pypi.python.org/packages/source/p/pygraphviz/pygraphviz-1.0rc2.zip#md5=f2c3ea804fffe4c902c92753238931a5 (from https://pypi.python.org/simple/pygraphviz/), version 1.0rc2 is a pre-release (use --pre to allow).
  Ignoring link https://pypi.python.org/packages/source/p/pygraphviz/pygraphviz-1.0rc3.tar.gz#md5=fbe24ba9e3cf8fc9705e7acbc582f63d (from https://pypi.python.org/simple/pygraphviz/), version 1.0rc3 is a pre-release (use --pre to allow).
  Ignoring link https://pypi.python.org/packages/source/p/pygraphviz/pygraphviz-1.0rc3.zip#md5=1aab6d8e039041655e6bdd0789fb2313 (from https://pypi.python.org/simple/pygraphviz/), version 1.0rc3 is a pre-release (use --pre to allow).
  Ignoring link https://pypi.python.org/packages/source/p/pygraphviz/pygraphviz-1.0rc4.tar.gz#md5=9d2d2e04e86bde7699db22cd19758424 (from https://pypi.python.org/simple/pygraphviz/), version 1.0rc4 is a pre-release (use --pre to allow).
  Ignoring link https://pypi.python.org/packages/source/p/pygraphviz/pygraphviz-1.0rc4.zip#md5=669ece9e6cc2eed1826b61eee854cb28 (from https://pypi.python.org/simple/pygraphviz/), version 1.0rc4 is a pre-release (use --pre to allow).
  Ignoring link https://pypi.python.org/packages/source/p/pygraphviz/pygraphviz-1.0rc5.tar.gz#md5=5853cde70a1a26a3b1922ce90759f5d7 (from https://pypi.python.org/simple/pygraphviz/), version 1.0rc5 is a pre-release (use --pre to allow).
  Ignoring link https://pypi.python.org/packages/source/p/pygraphviz/pygraphviz-1.0rc5.zip#md5=908f0127a72c441faa650f6f9d7cdb17 (from https://pypi.python.org/simple/pygraphviz/), version 1.0rc5 is a pre-release (use --pre to allow).
  Ignoring link https://pypi.python.org/packages/source/p/pygraphviz/pygraphviz-1.0rc6.tar.gz#md5=a8bafcfbd1b4c039dd116d53871e5fcc (from https://pypi.python.org/simple/pygraphviz/), version 1.0rc6 is a pre-release (use --pre to allow).
  Ignoring link https://pypi.python.org/packages/source/p/pygraphviz/pygraphviz-1.0rc6.zip#md5=0d7b2e76d6914b0e3e58d6a99933919a (from https://pypi.python.org/simple/pygraphviz/), version 1.0rc6 is a pre-release (use --pre to allow).
  Ignoring link https://pypi.python.org/packages/source/p/pygraphviz/pygraphviz-1.1rc1.tar.gz#md5=7e709a8bf8d5103b461a5f54a399ef0d (from https://pypi.python.org/simple/pygraphviz/), version 1.1rc1 is a pre-release (use --pre to allow).
  Ignoring link https://pypi.python.org/packages/source/p/pygraphviz/pygraphviz-1.1rc1.zip#md5=cb5b015ad61eb200ab40003481f620e2 (from https://pypi.python.org/simple/pygraphviz/), version 1.1rc1 is a pre-release (use --pre to allow).
  Using version 1.2 (newest of versions: 1.2, 1.2, 1.1, 1.1, 1.0, 1.0, 0.99.1, 0.99.1, 0.99, 0.99, 0.37, 0.37, 0.36, 0.36, 0.35, 0.35, 0.34, 0.34)
  Downloading from URL https://pypi.python.org/packages/source/p/pygraphviz/pygraphviz-1.2.tar.gz#md5=dbe3fa55e59a5d7e3bd924511b3275c4 (from https://pypi.python.org/simple/pygraphviz/)
  Running setup.py (path:/tmp/pip_build_mkaysi/pygraphviz/setup.py) egg_info for package pygraphviz
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/tmp/pip_build_mkaysi/pygraphviz/setup.py", line 23
        print "To install, run 'python setup.py install'"
                                                        ^
    SyntaxError: invalid syntax
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "/tmp/pip_build_mkaysi/pygraphviz/setup.py", line 23

    print "To install, run 'python setup.py install'"

                                                    ^

SyntaxError: invalid syntax

----------------------------------------
Cleaning up...
  Removing temporary dir /tmp/pip_build_mkaysi...
Command python setup.py egg_info failed with error code 1 in /tmp/pip_build_mkaysi/pygraphviz
Exception information:
Traceback (most recent call last):
  File "/home/users/mkaysi/.pyenv/versions/3.3.5/lib/python3.3/site-packages/pip-1.5.4-py3.3.egg/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/home/users/mkaysi/.pyenv/versions/3.3.5/lib/python3.3/site-packages/pip-1.5.4-py3.3.egg/pip/commands/install.py", line 278, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "/home/users/mkaysi/.pyenv/versions/3.3.5/lib/python3.3/site-packages/pip-1.5.4-py3.3.egg/pip/req.py", line 1229, in prepare_files
    req_to_install.run_egg_info()
  File "/home/users/mkaysi/.pyenv/versions/3.3.5/lib/python3.3/site-packages/pip-1.5.4-py3.3.egg/pip/req.py", line 325, in run_egg_info
    command_desc='python setup.py egg_info')
  File "/home/users/mkaysi/.pyenv/versions/3.3.5/lib/python3.3/site-packages/pip-1.5.4-py3.3.egg/pip/util.py", line 697, in call_subprocess
    % (command_desc, proc.returncode, cwd))
pip.exceptions.InstallationError: Command python setup.py egg_info failed with error code 1 in /tmp/pip_build_mkaysi/pygraphviz
```

**Comment by raghavrv** [comment]
Sometimes this error occurs when config is not loaded... 

Doing `install pkg-config` fixed this error for me...

**Comment by iulianstana** [comment]
For me it worked after I installed the `graphviz` package:

Doing `sudo apt-get install graphviz` .
