### ISSUE TITLE
ImportError: No module named '_graphviz'

### ISSUE THREAD

**Issue by davidmargolis** [pygraphviz/pygraphviz#227]
# Summary
Running command `import pygraphviz as pgv` in python interpreter causes error: `ImportError: No module named '_graphviz'`

# System info
*  Running on macOS Version 10.15.5.
*  Python3 version 3.8.3

# Installation
1. Install graphviz (version 2.44.0) via command `brew install graphviz`
1. Install pygraphviz (version) via command `pip install --user --install-option="--include-path=/usr/local/include" --install-option="--library-path=/usr/local/lib" pygraphviz`

# Running via `python3` Interpreter
```
>>> import pygraphviz as pgv
Traceback (most recent call last):
  File "/Users/USERNAME/Library/Python/3.7/lib/python/site-packages/pygraphviz/graphviz.py", line 18, in swig_import_helper
    fp, pathname, description = imp.find_module('_graphviz', [dirname(__file__)])
  File "/usr/local/Cellar/python@3.8/3.8.3_1/Frameworks/Python.framework/Versions/3.8/lib/python3.8/imp.py", line 296, in find_module
    raise ImportError(_ERR_MSG.format(name), name=name)
ImportError: No module named '_graphviz'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/USERNAME/Library/Python/3.7/lib/python/site-packages/pygraphviz/__init__.py", line 58, in <module>
    from .agraph import AGraph, Node, Edge, Attribute, ItemAttribute, DotError
  File "/Users/USERNAME/Library/Python/3.7/lib/python/site-packages/pygraphviz/agraph.py", line 22, in <module>
    from . import graphviz as gv
  File "/Users/USERNAME/Library/Python/3.7/lib/python/site-packages/pygraphviz/graphviz.py", line 28, in <module>
    _graphviz = swig_import_helper()
  File "/Users/USERNAME/Library/Python/3.7/lib/python/site-packages/pygraphviz/graphviz.py", line 20, in swig_import_helper
    import _graphviz
ModuleNotFoundError: No module named '_graphviz'
```

**Comment by jarrodmillman** [comment]
It looks like you are trying to use both ``Python/3.7`` and ``python@3.8/3.8.3_1``.  You may want to remove one or use virtual environments to keep them separate.

**Comment by davidmargolis** [comment]
Oh you were right! good observation @jarrodmillman ! My pip was linked to python 3.7 while the python version version I was running for the interpreter was 3.8. I ran the commands `brew upgrade python` and `brew upgrade pip`. And then updated my symbolic link for pip `ln -s /usr/local/Cellar/python@3.8/3.8.3_2/bin/pip3 /usr/local/bin/pip`
