### ISSUE TITLE
graph.delete_nodes_from() throws a key error for nodes that are in the graph (v1.7)

### ISSUE THREAD

**Issue by serenalotreck** [pygraphviz/pygraphviz#355]
I'm trying to remove nodes from an `AGraph` instance if they are not connected to any of a given set of keywords. When I provide a list of nodes to remove, I get the following traceback: 

```
Traceback (most recent call last):
  File "/mnt/home/lotrecks/anaconda3/envs/kg/lib/python3.8/site-packages/pygraphviz/agraph.py", line 1847, in __new__
    nh = gv.agnode(graph.handle, n.encode(graph.encoding), _Action.find)
  File "/mnt/home/lotrecks/anaconda3/envs/kg/lib/python3.8/site-packages/pygraphviz/graphviz.py", line 100, in agnode
    return _graphviz.agnode(g, name, createflag)
KeyError: 'agnode: no key'


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "minimal_example.py", line 28, in <module>
    if keyword in graph_copy.predecessors(node) \
  File "/mnt/home/lotrecks/anaconda3/envs/kg/lib/python3.8/site-packages/pygraphviz/agraph.py", line 870, in predecessors
    return list(self.predecessors_iter(n))
  File "/mnt/home/lotrecks/anaconda3/envs/kg/lib/python3.8/site-packages/pygraphviz/agraph.py", line 825, in predecessors_iter
    n = Node(self, n)
  File "/mnt/home/lotrecks/anaconda3/envs/kg/lib/python3.8/site-packages/pygraphviz/agraph.py", line 1849, in __new__
    raise KeyError(f"Node {n} not in graph.")
KeyError: 'Node internal standard not in graph.'
```
However, when I added a print statement right before this line in the code to check if the node were really not in the graph, I saw that it was indeed in the graph. I've simplified my code to reproduce the error: 
```
"""
Code to reproduce an error where pygraphviz says that it cannot remove a node
from the graph because it's not there, but it is there.
"""
import pygraphviz as pgv

if __name__ == '__main__':

    # Read in DOT file 
    dot_file = 'SciERC_graph_subset.dot'
    graph = pgv.AGraph(dot_file, directed=True)

    # Copy the graph and check for connections to keywords
    graph_copy = graph.copy()
    keywords = ['photosynthesis', 'pathways']

    for node in graph_copy.nodes():

        # If the node isn't a keyword, check if it's connected to one
        if node not in keywords:

            connected = False
            done = False

            for keyword in keywords:

                while not done:
                    if keyword in graph_copy.predecessors(node) \
                                or graph_copy.successors(node):

                        connected = True 
                        done = True
                    done = True

            if not connected:

                all_connections = graph_copy.predecessors(node) + \
                                    graph_copy.successors(node)
                print(f'all nodes: {graph_copy.nodes()}')
                print(f'all_connections: {all_connections}')
                in_nodes = [True for connection in all_connections if connection in graph_copy.nodes()]
                all_in = all(in_nodes)
                print(f'Are all nodes in the connections list also in the graph? {all_in}')
                
                graph_copy.delete_nodes_from(all_connections)
```
The printed output from this code right before the error is: 

```
all nodes: ['protocol', 'sensitivity', 'method', 'internal standard', 'selectivity', 'accuracy', 'precision', 'jasmonates', 'hormones', 'HnAOC', 'heterologous AOC gene', 'overexpression of nicotine biosynthetic pathway genes', 'approach', 'production of valuable secondary metabolites', 'metabolic engineering', 'viral pathogenicity', 'host defense', 'viral - betasatellite interactions', '- betasatellite interactions', 'virus - host interactions', '- host interactions', 'RNA -', 'differentially expressed genes', '-', '- seq', 'TbCSV', 'TbCSB', 'Y35AB', 'Y35A', 'GO and KEGG analyses', 'DEGs', 'biological process', 'cellular component', 'molecular function', 'pathways', 'CK', 'metabolic pathways', 'carbon metabolism', 'photosynthesis', 'Glyoxylate and dicarboxylate metabolism', 'DNA replication', 'Y35A treatment', 'Y35AB treatment']
all_connections: ['sensitivity', 'internal standard', 'selectivity', 'accuracy', 'precision']
Are all nodes in the connections list also in the graph? True
```
and you can see that 'internal standard' is in both lists, but it causes an error when its removal is attempted. This doesn't happen with the first node in the list, but it consistently happens with 'internal standard', and I can't figure out why. 

---------------------------
The DOT file: 

```
digraph {
    "high - performance thin - layer chromatography" -> "protocol" [ label="USED-FOR", weight=1 ];
    "sensitivity" -> "method" [ label="EVALUATE-FOR", weight=7 ];
    "internal standard" -> "method" [ label="USED-FOR", weight=1 ];
    "selectivity" -> "method" [ label="EVALUATE-FOR", weight=2 ];
    "selectivity" -> "accuracy" [ label="CONJUNCTION", weight=1 ];
    "selectivity" -> "precision" [ label="CONJUNCTION", weight=1 ];
    "accuracy" -> "method" [ label="EVALUATE-FOR", weight=6 ];
    "precision" -> "method" [ label="EVALUATE-FOR", weight=10 ];
    "jasmonates" -> "hormones" [ label="HYPONYM-OF", weight=1 ];
    "HnAOC" -> "heterologous AOC gene" [ label="HYPONYM-OF", weight=14 ];
    "HnAOC" -> "overexpression of nicotine biosynthetic pathway genes" [ label="USED-FOR", weight=1 ];
    "approach" -> "production of valuable secondary metabolites" [ label="USED-FOR", weight=1 ];
    "metabolic engineering" -> "production of valuable secondary metabolites" [ label="USED-FOR", weight=1 ];
    "viral pathogenicity" -> "host defense" [ label="CONJUNCTION", weight=1 ];
    "host defense" -> "viral - betasatellite interactions" [ label="CONJUNCTION", weight=1 ];
    "host defense" -> "- betasatellite interactions" [ label="CONJUNCTION", weight=1 ];
    "viral - betasatellite interactions" -> "virus - host interactions" [ label="CONJUNCTION", weight=1 ];
    "viral - betasatellite interactions" -> "- host interactions" [ label="CONJUNCTION", weight=1 ];
    "- betasatellite interactions" -> "virus - host interactions" [ label="CONJUNCTION", weight=1 ];
    "- betasatellite interactions" -> "- host interactions" [ label="CONJUNCTION", weight=1 ];
    "RNA -" -> "differentially expressed genes" [ label="USED-FOR", weight=3 ];
    "-" -> "differentially expressed genes" [ label="USED-FOR", weight=4 ];
    "- seq" -> "differentially expressed genes" [ label="USED-FOR", weight=4 ];
    "TbCSV" -> "TbCSV" [ label="CONJUNCTION", weight=1 ];
    "TbCSV" -> "TbCSB" [ label="CONJUNCTION", weight=1 ];
    "Y35AB" -> "Y35A" [ label="COMPARE", weight=1 ];
    "GO and KEGG analyses" -> "DEGs" [ label="USED-FOR", weight=1 ];
    "biological process" -> "cellular component" [ label="CONJUNCTION", weight=1 ];
    "cellular component" -> "Y35A" [ label="CONJUNCTION", weight=1 ];
    "cellular component" -> "molecular function" [ label="CONJUNCTION", weight=2 ];
    "Y35AB" -> "Y35A" [ label="CONJUNCTION", weight=1 ];
    "pathways" -> "Y35AB" [ label="PART-OF", weight=1 ];
    "pathways" -> "CK" [ label="PART-OF", weight=1 ];
    "metabolic pathways" -> "Y35AB" [ label="PART-OF", weight=1 ];
    "metabolic pathways" -> "carbon metabolism" [ label="CONJUNCTION", weight=1 ];
    "metabolic pathways" -> "photosynthesis" [ label="CONJUNCTION", weight=1 ];
    "carbon metabolism" -> "photosynthesis" [ label="CONJUNCTION", weight=2 ];
    "Glyoxylate and dicarboxylate metabolism" -> "DNA replication" [ label="CONJUNCTION", weight=1 ];
    "Y35A treatment" -> "Y35AB treatment" [ label="CONJUNCTION", weight=1 ];
}
```
----------------------
Also, I fully recognize my code is slightly heinous, and I was wondering if there was a way to do this with `subgraph`, but I wasn't able to figure out from the documentation if I could do that, so if folks have thoughts, I would appreciate it!

**Comment by dschult** [comment]
Looks like some bugs in your code... The error is not being rasied where you think it is. The nodes are deleted just fine, but then the error gets raised on the next iteration of the loop. If you are going to delete nodes, you had better check that the loop accounts for that.

Also, be careful with your syntax. You can't check is some `n` is in one of 2 containers A, B by saying `n in A or B`

**Comment by serenalotreck** [comment]
Thank you!! Didn't catch those -- added an `if` statement to check if the node had been deleted or not, and that fixed it.
