### ISSUE TITLE
pytest, TypeError: 'NoneType' object is not callable

### ISSUE THREAD

**Issue by irusland** [pygraphviz/pygraphviz#357]
The code

```python
import pytest as pytest
from pygraphviz import AGraph


@pytest.fixture()
def graph() -> AGraph:
    return AGraph()


def test_graph(graph):
    graph.nodes()
```

produces a output of 
```
Exception ignored in: <function AGraph.__del__ at 0x10ae27ee0>
Traceback (most recent call last):
  File "/Users/r.sirazhetdinov/work/dialog_platform/.venv/lib/python3.9/site-packages/pygraphviz/agraph.py", line 283, in __del__
  File "/Users/r.sirazhetdinov/work/dialog_platform/.venv/lib/python3.9/site-packages/pygraphviz/agraph.py", line 1000, in _close_handle
TypeError: 'NoneType' object is not callable
```

the solution is to change fixture to 
```python
@pytest.fixture()
def graph() -> AGraph:
    _graph = AGraph()
    yield _graph
    _graph.__del__()
```

Versions:
pytest = "6.2.4"
Python = "3.9.5"
pygraphviz = "1.7"

**Comment by rossbar** [comment]
I don't see this with the same pytest, Python, & pygraphviz versions. If I add the following test (in, say, `test_mytest.py`):

```python
import pytest as pytest                                                         
from pygraphviz import AGraph                                                   
                                                                                
                                                                                
@pytest.fixture                                                                 
def graph():                                                                    
    return AGraph()                                                             
                                                                                
                                                                                
def test_graph(graph):                                                          
    graph.nodes()
```

and call with `pytest test_mytest.py` I get no failures.

The main differences I notice are:
 - decorator calling pattern
 - platform (I'm on Linux, from the file structure it appears you're using macOS)
 - Type annotations - this shouldn't be a problem, though note that pygraphviz currently doesn't provide any static type checking.

**Comment by irusland** [comment]
Thanks for reply!
