### ISSUE TITLE
unexpected keyword argument 'strict'

### ISSUE THREAD

**Issue by balqui** [pygraphviz/pygraphviz#363]
Hello.The program below raises a surprising (to me) error in add_subgraph; am I doing anything wrong?

I found a workaround and can go on with our project so nothing depends on this, but decided to let you know anyway. Thanks for all your efforts.

B.

Traceback (most recent call last):
  File "r.py", line 26, in <module>
    d = D()
  File "r.py", line 24, in __init__
    self.add_subgraph(["a", "b"], name = 'cluster_a_b')
  File "/usr/local/lib/python3.6/dist-packages/pygraphviz/agraph.py", line 1044, in add_subgraph
    **attr)
TypeError: __init__() got an unexpected keyword argument 'strict'

This is the source r.py, running on Ubuntu 18.04 LTS and Python 3.6.9:

'''
Smallish example for what appears to be a pygraphviz runtime error
'''

from pygraphviz import AGraph

# this works well:

dd = AGraph(name = "test", compound = "true", directed = "true", newrank = "true")
dd.add_node("a", shape = "point")
dd.add_node("b", shape = "point")
dd.add_subgraph(["a", "b"], name = 'cluster_a_b')

# but a similar thing on an inheriting class raises an error upon the subgraph call:

class D(AGraph):
    
    def __init__(self):
        super().__init__(name = "test", compound = "true", directed = "true", newrank = "true")
        # alternative, same outcome:
        # AGraph.__init__(self, name = "test", compound = "true", directed = "true", newrank = "true")
        self.add_node("a", shape = "point")
        self.add_node("b", shape = "point")
        self.add_subgraph(["a", "b"], name = 'cluster_a_b')

d = D()

**Comment by lucas-sonnabend** [comment]
Hello,
I'd like to take a stab at this, if possible

**Comment by lucas-sonnabend** [comment]
okay, I think the problem here is the add_subgraph call. That creates a subgraph by calling `self.__class__(strict=True, ...)`

so maybe putting that in an init method is not the best idea

**Comment by balqui** [comment]
Thanks a lot for your help, Lucas. I don't really understand, actually. At
H = self.__class__(
            strict=self.strict, directed=self.directed, handle=handle, name=name, **attr
        )
inside add_subgraph() the init of self.__class__ looks to me like a standard graph init, inherited, that should allow for a kw arg "strict". Also, a programmer writing my snippet may well not have even heard of the strict graph attribute so the message is very puzzling.
Anyway, your efforts are appreciated.

**Comment by dschult** [comment]
In this case `self.__class__` is the class `D`. It is not the inherited `__init__` that is called. It is the subclassed `__init__` you are writing. And that has no input argument `strict.

**Comment by balqui** [comment]
Many thanks. I understand now. Then, as I see it, the bottom line is that one cannot subclass AGraph and provide the subclass with a specific ```_init__()``` overloading ```AGraph.__init__()``` - instead the subclass must keep ```AGraph().__init__()``` as is, otherwise the calls to ```add_subgraph()``` will fail and, conceivably, other methods using similarly ```self.__class__``` might fail likewise. I still see no reason why ```self.__class__``` is adequate at that point but this goes far beyond my abilities. Thanks again to Dan and Lukas for their help.

**Comment by dschult** [comment]
Your subclass can add extra input arguments, but not remove arguments needed for the base class. You should include a keyword argument in your subclass for "strict" and then handle that input argument however you like (for example, by ignoring it).

**Comment by rossbar** [comment]
I agree with @dschult . The way to fix this problem with the current design is to add the ability to handle arbitrary keywords to the constructor, e.g.

```python
class D(AGraph):
    def __init__(self, **kwargs):
        super().__init__(name="test", compound="true", directed="true", newrank="true")
```

There are ways this could be "improved", but the first question is to answer what the behavior *should* be. For example, if you subclass `AGraph`, do you expect subgraphs within your derived class to instances of your derived class, or of `AGraph`? If the answer is "my derived class", then I think you have to design your subclass in such a way that it can handle this scenario.

**Comment by balqui** [comment]
Learning a lot thanks to all of you. Very much appreciated, everyone!
