### ISSUE TITLE
Unable to run pygraphviz after upgrading OS to macOS Monterey (12.3.1)

### ISSUE THREAD

**Issue by YuxinSun** [pygraphviz/pygraphviz#403]
I had both graphviz and pygraphviz successfully installed and run on my Mac (Big Sur). After upgrading my OS to Monterey last week, pygraphviz stopped working. Here are some test code under pygraphviz version 1.9:

```
import pygraphviz as pgv
a = pgv.AGraph() 
print(a._get_prog('neato'))
```

And I got the error:

```
Traceback (most recent call last):
  File "/Users/usr_name/Documents/py_virtual_env/lib/python3.10/site-packages/pygraphviz/agraph.py", line 1356, in _get_prog
    runprog = self._which(prog)
  File "/Users/usr_name/Documents/py_virtual_env/lib/python3.10/site-packages/pygraphviz/agraph.py", line 1812, in _which
    raise ValueError(f"No prog {name} in path.")
ValueError: No prog neato in path.
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/Users/usr_name/Documents/py_virtual_env/lib/python3.10/site-packages/pygraphviz/agraph.py", line 1358, in _get_prog
    raise ValueError(f"Program {prog} not found in path.")
ValueError: Program neato not found in path.
```

I've tried to upgrade graphviz with Homebrew and reinstall pygraphviz with solutions like #398 and [this one](https://stackoverflow.com/questions/69970147/how-do-i-resolve-the-pygraphviz-error-on-mac-os) but nothing worked.

```neato``` can be found in ```/usr/local/bin/neato``` and ```graphviz``` in ```/usr/local/Cellar/graphviz/3.0.0```.

**Comment by YuxinSun** [comment]
Thanks for the reply, this solves the problem!

```echo $PATH``` does return ```usr/local/bin```, but ```os.environ['PATH']``` doesn't seem to contain it. I added the following lines at the beginning of my Python script and it worked:

```
import os
os.environ['PATH'] += os.pathsep + '/usr/local/bin'
```
