### ISSUE TITLE
1.9: issue with circular import on generate documentation

### ISSUE THREAD

**Issue by kloczek** [pygraphviz/pygraphviz#409]
Looks like it is some code issue which blocks generate documentation
<details>

```console
[tkloczko@devel-g2v doc]$ make html
#make latex
#make -C build/latex all-pdf
#cp build/latex/pygraphviz.pdf source/.
sphinx-build -b html -d build/doctrees   source build/html
Running Sphinx v4.5.0

Configuration error:
There is a programmable error in your configuration file:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/sphinx/config.py", line 332, in eval_config_file
    exec(code, namespace)
  File "/home/tkloczko/rpmbuild/BUILD/pygraphviz-pygraphviz-1.9/doc/source/conf.py", line 63, in <module>
    import pygraphviz
  File "/home/tkloczko/rpmbuild/BUILD/pygraphviz-pygraphviz-1.9/pygraphviz/__init__.py", line 24, in <module>
    from .agraph import AGraph, Node, Edge, Attribute, ItemAttribute, DotError
  File "/home/tkloczko/rpmbuild/BUILD/pygraphviz-pygraphviz-1.9/pygraphviz/agraph.py", line 15, in <module>
    from . import graphviz as gv
  File "/home/tkloczko/rpmbuild/BUILD/pygraphviz-pygraphviz-1.9/pygraphviz/graphviz.py", line 13, in <module>
    from . import _graphviz
ImportError: cannot import name '_graphviz' from partially initialized module 'pygraphviz' (most likely due to a circular import) (/home/tkloczko/rpmbuild/BUILD/pygraphviz-pygraphviz-1.9/pygraphviz/__init__.py)

make: *** [Makefile:61: html] Error 2
```
</details>

**Comment by rossbar** [comment]
This likely stems from the same build problem noted in #410, so landing on a working build/install/test workflow will likely resolve this. I will close this so that we can consolidate the conversation in a single thread.
