### ISSUE TITLE
ImportError: symbol not found in flat namespace '_Agdirected'

### ISSUE THREAD

**Issue by YuxinSun** [pygraphviz/pygraphviz#483]
Edit: added mac chip version and python version details.

Hi I've installed both graphviz and pygraphviz but was unable to import pygraphviz in Python.

mac chip: Apple M2 Max
mac OS: Ventura 13.0 (22A8380)
graphviz ver: 9.0.0
pygraphviz ver: 1.11
Python ver: 3.11.6

I installed graphviz using HomeBrew: `brew install graphviz`
And pygraphviz using pip. I tried two ways:
```
export GRAPHVIZ_DIR="$(brew --prefix graphviz)"
pip install pygraphviz \
    --global-option=build_ext \
    --global-option="-I$GRAPHVIZ_DIR/include" \
    --global-option="-L$GRAPHVIZ_DIR/lib"
```
and
```
python -m pip install \
    --global-option=build_ext \
    --global-option="-I$(brew --prefix graphviz)/include/" \
    --global-option="-L$(brew --prefix graphviz)/lib/" \
    pygraphviz
```
But received the same error when importing pygraphviz. The full error message was:

```
Traceback (most recent call last):
  File "/Applications/PyCharm CE.app/Contents/plugins/python-ce/helpers/pydev/pydevconsole.py", line 364, in runcode
    coro = func()
           ^^^^^^
  File "<input>", line 1, in <module>
  File "/Applications/PyCharm CE.app/Contents/plugins/python-ce/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/xx/Documents/python/py 3.11/lib/python3.11/site-packages/pygraphviz/__init__.py", line 24, in <module>
    from .agraph import AGraph, Node, Edge, Attribute, ItemAttribute, DotError
  File "/Applications/PyCharm CE.app/Contents/plugins/python-ce/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/xx/Documents/python/py 3.11/lib/python3.11/site-packages/pygraphviz/agraph.py", line 15, in <module>
    from . import graphviz as gv
  File "/Applications/PyCharm CE.app/Contents/plugins/python-ce/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/xx/Documents/python/py 3.11/lib/python3.11/site-packages/pygraphviz/graphviz.py", line 10, in <module>
    from . import _graphviz
  File "/Applications/PyCharm CE.app/Contents/plugins/python-ce/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ImportError: dlopen(/Users/xx/Documents/python/py 3.11/lib/python3.11/site-packages/pygraphviz/_graphviz.cpython-311-darwin.so, 0x0002): symbol not found in flat namespace '_Agdirected'

```

Any help is very appreciated, thanks very much!

**Comment by MridulS** [comment]
I haven't looked too much into this but this looks similar to previous issues where there is a mismatch between graphviz versions. A quick solution could be to use `conda` instead of `pip` here to install pygraphviz (graphviz is installed via conda then).

Could you try `conda install --channel conda-forge pygraphviz` (this will also install graphviz for you, so you don't need homebrew to manage that)?

**Comment by YuxinSun** [comment]
Thanks this solved the problem!

For those who may have the same problem in the future, the versions installed by conda are:

graphviz: 2.50.0
pygraphviz: 1.9
