### ISSUE TITLE
import error

### ISSUE THREAD

**Issue by niannianQAQ** [pygraphviz/pygraphviz#523]
Hi everyone, this is my first time asking a question on GitHub.

I've installed graphviz0.18 in Pycharm and graphviz-install-2.50.0-win64 in my computer, and the pm4py version is 2.2.3 and the python version is 3.9.
 I receive this message error:
```
Traceback (most recent call last):
  File "D:\chatbot-process-mining\chatbot_evaluation.py", line 6, in <module>
    import pm4py
  File "D:\chatbot-process-mining\venv\lib\site-packages\pm4py\__init__.py", line 20, in <module>
    from pm4py import util, objects, statistics, algo, visualization
  File "D:\chatbot-process-mining\venv\lib\site-packages\pm4py\visualization\__init__.py", line 21, in <module>
    from pm4py.visualization import common, dfg, petrinet, process_tree, transition_system, decisiontree, align_table, \
  File "D:\chatbot-process-mining\venv\lib\site-packages\pm4py\visualization\common\__init__.py", line 17, in <module>
    from pm4py.visualization.common import save, utils, gview, visualizer
  File "D:\chatbot-process-mining\venv\lib\site-packages\pm4py\visualization\common\gview.py", line 21, in <module>
    from graphviz.dot import Digraph
ImportError: cannot import name 'Digraph' from 'graphviz.dot' (D:\chatbot-process-mining\venv\lib\site-packages\graphviz\dot.py)
```
gview.py line 21:
```
19 from pm4py.util import vis_utils, constants
20 from io import BytesIO
21 from graphviz.dot import Digraph
```

**Comment by rossbar** [comment]
This is the issue tracker for `pygraphviz` - it looks like you're using a different project: https://pypi.org/project/graphviz/. Consider opening an issue there instead!

**Comment by niannianQAQ** [comment]
> 这是问题跟踪器 - 看起来您正在使用不同的项目：https://pypi.org/project/graphviz/。考虑在那里打开一个问题！`pygraphviz`

thank you!
