### ISSUE TITLE
wheels for pygraphviz (.whl))

### ISSUE THREAD

**Issue by Kenneth1995-star** [pygraphviz/pygraphviz#545]
i wish to install pygrahviz in my computer to visualize a coupled CBD created and for that i need pyraphviz wheels (.whl) installed in order to visualize. please help

**Comment by ManPython** [comment]
I made this steps:
```
python -m pip install --config-settings="--global-option=build_ext" `
              --config-settings="--global-option=-IC:\Program Files\Graphviz\include" `
              --config-settings="--global-option=-LC:\Program Files\Graphviz\lib" `
              pygraphviz
```
Then
```
Python 3.11.3 (tags/v3.11.3:f3909b8, Apr  4 2023, 23:49:59) [MSC v.1934 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import pygraphviz as pgv
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "E:\Python311-venv\Lib\site-packages\pygraphviz\__init__.py", line 24, in <module>
    from .agraph import AGraph, Node, Edge, Attribute, ItemAttribute, DotError
  File "E:\Python311-venv\Lib\site-packages\pygraphviz\agraph.py", line 17, in <module>
    from . import graphviz as gv
  File "E:\Python311-venv\Lib\site-packages\pygraphviz\graphviz.py", line 10, in <module>
    from . import _graphviz
ImportError: DLL load failed while importing _graphviz: Can't find module
```

**Comment by robtaylor** [comment]
I recommend using [cibuildwheel](https://github.com/pypa/cibuildwheel) for cross building and publishing wheels. Its quite easy to set up a github workflow for this:  https://cibuildwheel.pypa.io/en/1.x/setup/#github-actions

**Comment by rossbar** [comment]
> I recommend using [cibuildwheel](https://github.com/pypa/cibuildwheel) for cross building and publishing wheels. Its quite easy to set up a github workflow for this: https://cibuildwheel.pypa.io/en/1.x/setup/#github-actions

Oh we're trying :) - see e.g. #553, #555. The challenge is not in the build infrastructure, but in incorporating the necessary components of graphviz - it's not as straightforward as a typical cibuildwheel workflow. If you have experience with library linking on windows, any insights in #558 would certainly be helpful!

**Comment by robtaylor** [comment]
Can you build graphviz statically and hard link the plugins?

Happy to help on Mac - I think better to use homebrew than macports tho!

**Comment by chunqishi** [comment]
Here it works for me.  
`python -m pip install --use-pep517 --config-setting="--global-option=build_ext"  --config-setting="--global-option=-IC:\Program Files\Graphviz\include"  --config-setting="--global-option=-LC:\Program Files\Graphviz\lib"   pygraphviz`

**Comment by MridulS** [comment]
Alrighty - We have some wheels finally! It would be great if folks can test these wheels out locally and report if they run into any issues: https://pypi.org/project/pygraphviz/2.0rc1/

You can try this out with:
`pip install pygraphviz==2.0rc1` or `pip install -U --pre pygraphviz`

**Comment by rossbar** [comment]
pygraphviz 2.0 has been released, so this particular installation issue should no longer be relevant. If you experience installation issues with pygraphviz 2.0, please open a new issue!
