### ISSUE TITLE
get_node() can't find nodes specified via html labels, also edges() result is incorrect

### ISSUE THREAD

**Issue by mulkieran** [pygraphviz/pygraphviz#76]
Given a standard example from the graphviz documentation for HTML style tags...

```
digraph structs {
    node [shape=plaintext]
    struct1 [label=< <TABLE BORDER="0" CELLBORDER="1" CELLSPACING="0"> <TR><TD>left</TD><TD PORT="f1">mid dle</TD><TD PORT="f2">right</TD></TR> </TABLE>>];
    struct2 [label=< <TABLE BORDER="0" CELLBORDER="1" CELLSPACING="0"> <TR><TD PORT="f0">one</TD><TD>two</TD></TR> </TABLE>>];
    struct3 [label=< <TABLE BORDER="0" CELLBORDER="1" CELLSPACING="0" CELLPADDING="4"> <TR> <TD ROWSPAN="3">hello<BR/>world</TD> <TD COLSPAN="3">b</TD> <TD ROWSPAN="3">g</TD> <TD ROWSPAN="3">h</TD> </TR> <TR> <TD>c</TD><TD PORT="here">d</TD><TD>e</TD> </TR> <TR> <TD COLSPAN="3">f</TD> </TR> </TABLE>>];
    struct1:f1 -> struct2:f0;
    struct1:f2 -> struct3:here;
}
```

I load the file, and try to extract a node like "struct1:f1", i.e., a node that exists because it is a port on an HTML label.

```
>>> import pygraphviz
>>> G = pygraphviz.AGraph("junk.dot"
>>> G.get_node("struct1")
u'struct1'
>>> G.get_node("struct1:f1")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib64/python2.7/site-packages/pygraphviz/agraph.py", line 424, in get_node
    return Node(self, n)
  File "/usr/lib64/python2.7/site-packages/pygraphviz/agraph.py", line 1568, in __new__
    raise KeyError("Node %s not in graph." % n)
KeyError: u'Node struct1:f1 not in graph.'
>>> G.nodes()
[u'struct1', u'struct2', u'struct3']
>>> G.edges()
[(u'struct1', u'struct2'), (u'struct1', u'struct3')]
```

Note that the nodes are incomplete and the edges are incorrect as they do not take the ports into account.

`G.draw()` still draws the correct graph.

**Comment by aristotll** [comment]
I have a similar problem .

**Comment by hagberg** [comment]
Those are "ports" and show up as attributes on the edges.  They are there and can be manipulated through the edge attributes

```python
In [20]: list(G.get_edge('struct1','struct2').attr.items())
Out[20]: [('headport', 'f0'), ('tailport', 'f1')]
```
