### ISSUE TITLE
Can't install pygraphviz on Fedora 23

### ISSUE THREAD

**Issue by M5oul** [pygraphviz/pygraphviz#85]
I can't install pygraphviz via pip. Before, I installed graphviz `sudo dnf install graphviz` on Fedora 23, then
```bash
(env-sakia) [moul@moulinette sakia]$ pip install pygraphviz
Collecting pygraphviz
  Using cached pygraphviz-1.3.1.tar.gz
Installing collected packages: pygraphviz
  Running setup.py install for pygraphviz
    Complete output from command /home/moul/.pyenv/versions/env-sakia/bin/python3.5 -c "import setuptools, tokenize;__file__='/tmp/pip-build-r1mr5lt0/pygraphviz/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-r2va_ym2-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/moul/.pyenv/versions/env-sakia/include/site/python3.5/pygraphviz:
    running install
    Package libcgraph was not found in the pkg-config search path.
    Perhaps you should add the directory containing `libcgraph.pc'
    to the PKG_CONFIG_PATH environment variable
    No package 'libcgraph' found
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-r1mr5lt0/pygraphviz/setup.py", line 87, in <module>
        tests_require=['nose>=0.10.1', 'doctest-ignore-unicode>=0.1.0',],
      File "/home/moul/.pyenv/versions/3.5.0/lib/python3.5/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/home/moul/.pyenv/versions/3.5.0/lib/python3.5/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/home/moul/.pyenv/versions/3.5.0/lib/python3.5/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/tmp/pip-build-r1mr5lt0/pygraphviz/setup_commands.py", line 44, in modified_run
        self.include_path, self.library_path = get_graphviz_dirs()
      File "/tmp/pip-build-r1mr5lt0/pygraphviz/setup_extra.py", line 121, in get_graphviz_dirs
        include_dirs, library_dirs = _pkg_config()
      File "/tmp/pip-build-r1mr5lt0/pygraphviz/setup_extra.py", line 44, in _pkg_config
        output = S.check_output(['pkg-config', '--libs-only-L', 'libcgraph'])
      File "/home/moul/.pyenv/versions/3.5.0/lib/python3.5/subprocess.py", line 629, in check_output
        **kwargs).stdout
      File "/home/moul/.pyenv/versions/3.5.0/lib/python3.5/subprocess.py", line 711, in run
        output=stdout, stderr=stderr)
    subprocess.CalledProcessError: Command '['pkg-config', '--libs-only-L', 'libcgraph']' returned non-zero exit status 1
    Trying pkg-config
    
    ----------------------------------------
Command "/home/moul/.pyenv/versions/env-sakia/bin/python3.5 -c "import setuptools, tokenize;__file__='/tmp/pip-build-r1mr5lt0/pygraphviz/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-r2va_ym2-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/moul/.pyenv/versions/env-sakia/include/site/python3.5/pygraphviz" failed with error code 1 in /tmp/pip-build-r1mr5lt0/pygraphviz
```
You could find more information on https://github.com/ucoin-io/sakia/issues/208

**Comment by dschult** [comment]
It looks like "dnf install graphviz" has not put libcgraph in a place that
pkg-config can find it. Can you manually find where libcgraph is located
and add that to the locations that pkg-config searches?

**Comment by sandzwerg** [comment]
Had the same Problem on Fedora 22, you need to install "graphviz-devel-*" to fix it. A little hint that such a package could exist on some distributions could help.

**Comment by cacampbell** [comment]
Elementary OS Loki (Ubuntu-ish) also requires dev package

```
sudo apt-get install graphviz-dev
pip install pygraphviz
```

**Comment by Deafteen** [comment]
> Had the same Problem on Fedora 22, you need to install "graphviz-devel-*" to fix it. A little hint that such a package could exist on some distributions could help.

This helped me. Thank you so much!
